require "functions.NumberToggle"
require "functions.FormatJSON"
require "functions.GitPath"
require "autocommands.packer"
require "overrides.netrw"
require "overrides.quickfixlist"
require "overrides.vim"
require "extends.bindings"

require "plugins"
require "lsp"
