require "plugins/after/test"
require "plugins/after/telescope"
-- require "plugins/after/nnn"
require "plugins/after/spectre"
require "plugins/after/gitsigns"
require "plugins/after/theme"
require "plugins/after/colorizer"
require "plugins/after/lualine"
require "plugins/after/modes"
require "plugins/after/neogen"
